import 'package:flutter/material.dart';

void main() {
  runApp(const LoginPage());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class LoginPage extends StatelessWidget {
  const LoginPage({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          LogIn(),
        ]),
      ),
    );
  }
}

class LogIn extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 400,
          height: 844,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
          child: Stack(children: [
            Positioned(
              left: 22,
              top: 327,
              child: Container(
                width: 345,
                height: 60,
                child: Stack(
                  children: [
                    Positioned(
                      left: 0,
                      top: 0,
                      child: Container(
                        width: 345,
                        height: 60,
                        decoration: ShapeDecoration(
                          color: Color(0xFFD9D9D9),
                          shape: RoundedRectangleBorder(
                            side:
                                BorderSide(width: 2, color: Color(0xFFA7A5A6)),
                            borderRadius: BorderRadius.circular(20),
                          ),
                        ),
                      ),
                    ),
                    Positioned(
                      left: 17,
                      top: 19,
                      child: SizedBox(
                        width: 310,
                        child: Text(
                          'Username/Email Address',
                          style: TextStyle(
                            color: Color(0xFFA7A5A6),
                            fontSize: 20,
                            fontFamily: 'Judson',
                            fontWeight: FontWeight.w700,
                            height: 0,
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
            Positioned(
              left: 22,
              top: 407,
              child: Container(
                width: 345,
                height: 60,
                child: Stack(
                  children: [
                    Positioned(
                      left: 0,
                      top: 0,
                      child: Container(
                        width: 345,
                        height: 60,
                        decoration: ShapeDecoration(
                          color: Color(0xFFD9D9D9),
                          shape: RoundedRectangleBorder(
                            side:
                                BorderSide(width: 2, color: Color(0xFFA7A5A6)),
                            borderRadius: BorderRadius.circular(20),
                          ),
                        ),
                      ),
                    ),
                    Positioned(
                      left: 17,
                      top: 19,
                      child: SizedBox(
                        width: 310,
                        child: Text(
                          'Password',
                          style: TextStyle(
                            color: Color(0xFFA7A5A6),
                            fontSize: 20,
                            fontFamily: 'Judson',
                            fontWeight: FontWeight.w700,
                            height: 0,
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
            Positioned(
              left: 120,
              top: 646,
              child: Container(
                width: 150,
                height: 150,
                child: Stack(
                  children: [
                    Positioned(
                      left: 0,
                      top: 0,
                      child: Container(
                        width: 150,
                        height: 150,
                        decoration: BoxDecoration(
                          image: DecorationImage(
                            image: NetworkImage(
                                "https://via.placeholder.com/150x150"),
                            fit: BoxFit.fill,
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
            Positioned(
              left: 33,
              top: 160,
              child: Text(
                'CleanCycle',
                style: TextStyle(
                  color: Color(0xFFA7A5A6),
                  fontSize: 60,
                  fontFamily: 'Yeseva One',
                  fontWeight: FontWeight.w400,
                  height: 0,
                ),
              ),
            ),
            Positioned(left: 95, top: 521, child: newMethod(context)),
          ]),
        ),
      ],
    );
  }

  Container newMethod(BuildContext context) {
    return Container(
      width: 200,
      height: 60,
      child: Stack(
        children: [
          Positioned(
            left: 0,
            top: 0,
            child: Container(
              width: 200,
              height: 60,
              decoration: ShapeDecoration(
                color: Color(0xFFA7A5A6),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(20),
                ),
              ),
            ),
          ),
          Positioned(
            left: 10,
            top: 13,
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                ElevatedButton(
                  onPressed: () {
                    Navigator.pushNamed(context, '/login');
                  },
                  child: Text(
                    "Login",
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Color(0xFFD9D9D9),
                      fontSize: 30,
                      fontFamily: 'Judson',
                      fontWeight: FontWeight.w700,
                      height: 1,
                    ),
                  ),
                ),
              ],
            ),
          ),
          Positioned(
            left: 140,
            top: 591,
            child: Text(
              'or sign up',
              style: TextStyle(
                color: Color(0xFFD9D9D9),
                fontSize: 25,
                fontFamily: 'Judson',
                fontWeight: FontWeight.w700,
                height: 0,
              ),
            ),
          ),
          Positioned(
            left: 27,
            top: 239,
            child: Text(
              'Welcome back, [user type]!',
              style: TextStyle(
                color: Color(0xFFA7A5A6),
                fontSize: 30,
                fontStyle: FontStyle.italic,
                fontFamily: 'Judson',
                fontWeight: FontWeight.w400,
                height: 0,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
