import 'package:flutter/material.dart';

void main() {
  runApp(const Signup_page());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class Signup_page extends StatelessWidget {
  const Signup_page({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          SignUp(),
        ]),
      ),
    );
  }
}

class SignUp extends StatelessWidget {
  const SignUp({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(children: [
      Container(
          width: 390,
          height: 844,
          clipBehavior: Clip.antiAlias,
          decoration: const BoxDecoration(color: Color(0xFFD9D9D9)),
          child: Stack(
            children: [
              Positioned(
                left: 22,
                top: 424,
                child: SizedBox(
                  width: 345,
                  height: 60,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 345,
                          height: 60,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFD9D9D9),
                            shape: RoundedRectangleBorder(
                              side: const BorderSide(
                                  width: 2, color: Color(0xFFA7A5A6)),
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                        ),
                      ),
                      const Positioned(
                        left: 17,
                        top: 19,
                        child: SizedBox(
                          width: 310,
                          child: Text(
                            'Email Address',
                            style: TextStyle(
                              color: Color(0xFFA7A5A6),
                              fontSize: 20,
                              fontFamily: 'Judson',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 22,
                top: 205,
                child: SizedBox(
                  width: 345,
                  height: 60,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 345,
                          height: 60,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFD9D9D9),
                            shape: RoundedRectangleBorder(
                              side: const BorderSide(
                                  width: 2, color: Color(0xFFA7A5A6)),
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                        ),
                      ),
                      const Positioned(
                        left: 17,
                        top: 19,
                        child: SizedBox(
                          width: 310,
                          child: Text(
                            'First Name',
                            style: TextStyle(
                              color: Color(0xFFA7A5A6),
                              fontSize: 20,
                              fontFamily: 'Judson',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 22,
                top: 497,
                child: SizedBox(
                  width: 345,
                  height: 60,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 345,
                          height: 60,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFD9D9D9),
                            shape: RoundedRectangleBorder(
                              side: const BorderSide(
                                  width: 2, color: Color(0xFFA7A5A6)),
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                        ),
                      ),
                      const Positioned(
                        left: 17,
                        top: 19,
                        child: SizedBox(
                          width: 310,
                          child: Text(
                            'Password',
                            style: TextStyle(
                              color: Color(0xFFA7A5A6),
                              fontSize: 20,
                              fontFamily: 'Judson',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 22,
                top: 278,
                child: SizedBox(
                  width: 345,
                  height: 60,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 345,
                          height: 60,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFD9D9D9),
                            shape: RoundedRectangleBorder(
                              side: const BorderSide(
                                  width: 2, color: Color(0xFFA7A5A6)),
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                        ),
                      ),
                      const Positioned(
                        left: 17,
                        top: 19,
                        child: SizedBox(
                          width: 310,
                          child: Text(
                            'Last Name',
                            style: TextStyle(
                              color: Color(0xFFA7A5A6),
                              fontSize: 20,
                              fontFamily: 'Judson',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 22,
                top: 351,
                child: SizedBox(
                  width: 345,
                  height: 60,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 345,
                          height: 60,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFD9D9D9),
                            shape: RoundedRectangleBorder(
                              side: const BorderSide(
                                  width: 2, color: Color(0xFFA7A5A6)),
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                        ),
                      ),
                      const Positioned(
                        left: 17,
                        top: 19,
                        child: SizedBox(
                          width: 310,
                          child: Text(
                            'Username',
                            style: TextStyle(
                              color: Color(0xFFA7A5A6),
                              fontSize: 20,
                              fontFamily: 'Judson',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 120,
                top: 682,
                child: SizedBox(
                  width: 150,
                  height: 150,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 150,
                          height: 150,
                          decoration: const BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage(
                                  "https://via.placeholder.com/150x150"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              const Positioned(
                left: 33,
                top: 52,
                child: Text(
                  'CleanCycle',
                  style: TextStyle(
                    color: Color(0xFFA7A5A6),
                    fontSize: 60,
                    fontFamily: 'Yeseva One',
                    fontWeight: FontWeight.w400,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 95,
                top: 583,
                child: SizedBox(
                  width: 200,
                  height: 60,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 200,
                          height: 60,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFA7A5A6),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 10,
                        top: 13,
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            ElevatedButton(
                              onPressed: () {
                                Navigator.pushNamed(context, '/login');
                              },
                              child: Text(
                                "Sign up",
                                textAlign: TextAlign.center,
                                style: TextStyle(
                                  color: Color(0xFFD9D9D9),
                                  fontSize: 30,
                                  fontFamily: 'Judson',
                                  fontWeight: FontWeight.w700,
                                  height: 1,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      const Positioned(
                        left: 149,
                        top: 653,
                        child: Text(
                          'or log in',
                          style: TextStyle(
                            color: Color(0xFFD9D9D9),
                            fontSize: 25,
                            fontFamily: 'Judson',
                            fontWeight: FontWeight.w700,
                            height: 0,
                          ),
                        ),
                      ),
                      const Positioned(
                        left: 31,
                        top: 131,
                        child: Text(
                          'Welcome aboard, [user type]!',
                          style: TextStyle(
                            color: Color(0xFFA7A5A6),
                            fontSize: 27,
                            fontStyle: FontStyle.italic,
                            fontFamily: 'Judson',
                            fontWeight: FontWeight.w400,
                            height: 0,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ))
    ]);
  }
}
