// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2Xb8T7FZsxz4SOw8SKVkedvsKpsGEL24',
    appId: '1:1013558292992:web:4e55ee7394fb9902de9ee5',
    messagingSenderId: '1013558292992',
    projectId: 'clean-cycle-f61c2',
    authDomain: 'clean-cycle-f61c2.firebaseapp.com',
    storageBucket: 'clean-cycle-f61c2.appspot.com',
    measurementId: 'G-QYDVR9289V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIcWzbiiB-WncnxBJyRkpFACx7QU36NZQ',
    appId: '1:1013558292992:android:ce3bd0787c23b821de9ee5',
    messagingSenderId: '1013558292992',
    projectId: 'clean-cycle-f61c2',
    storageBucket: 'clean-cycle-f61c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6wBYQDjTxUMOOJwPUtWAT4sPWxDT1PrQ',
    appId: '1:1013558292992:ios:907376c87b08d5b8de9ee5',
    messagingSenderId: '1013558292992',
    projectId: 'clean-cycle-f61c2',
    storageBucket: 'clean-cycle-f61c2.appspot.com',
    iosBundleId: 'com.example.cleanCycle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6wBYQDjTxUMOOJwPUtWAT4sPWxDT1PrQ',
    appId: '1:1013558292992:ios:907376c87b08d5b8de9ee5',
    messagingSenderId: '1013558292992',
    projectId: 'clean-cycle-f61c2',
    storageBucket: 'clean-cycle-f61c2.appspot.com',
    iosBundleId: 'com.example.cleanCycle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2Xb8T7FZsxz4SOw8SKVkedvsKpsGEL24',
    appId: '1:1013558292992:web:5337d66c4f40a0e1de9ee5',
    messagingSenderId: '1013558292992',
    projectId: 'clean-cycle-f61c2',
    authDomain: 'clean-cycle-f61c2.firebaseapp.com',
    storageBucket: 'clean-cycle-f61c2.appspot.com',
    measurementId: 'G-0PSJZSFF1V',
  );
}
